server:
  port: ${PORT:8443}
  #address: local.localhost
  servlet:
    contextPath: /
  ssl:
    enabled: true
    #key-alias: local.localhost
    key-store-type: PKCS12
    key-store: config/ssl/key-store.pfx
    key-store-password: storepass
    trust-store-type: PKCS12
    trust-store: config/ssl/trust-store.pfx
    trust-store-password: storepass
    client-auth: want
app:
  route:
    api: ${API:/api/v1}
  proxy:
    enabled: false
    host: my.proxy
    port: 80
  certificates-enable:
          
security:
  headers:
    hsts: NONE

spring:
  #main:
  #  web-application-type: reactive
  profiles:
    active: homo
  messages:
    basename: i18n/messages
    encoding: UTF-8
  application:
    name: publisher-http-s3
  # En desarrollo para pruebas
  webflux:
    static-path-pattern: classpath:/static/**

# Storage S3
storage:
  s3:
    enabled: true
    accessKey: sandboxKey
    secretKey: sandboxSecret
    bucket: sandbox-bk
    endpoint: 172.240.49.25:9280
    ssl:
      enabled: false
      key-store: config/ssl/key-store-ceph.jks
      key-store-password: changeit
      trust-store: config/ssl/trust-store-ceph.jks
      trust-store-password: changeit

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: loggers
    #beans:
    #  cache:
    #    time-to-live: 10s
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 8091
    address: 127.0.0.1
    servlet:
      context-path: /
  security:
    enabled: false

# https://www.baeldung.com/spring-boot-info-actuator-custom
info:
  app:
    name: publisher-http-s3
  environment: desarrollo
  
logging:
  file: logs/publisher-http-s3.log
  level:
    root: INFO
